import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  stickersSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from the root of the stickers directory
    },
  ],
};

export default sidebars;